### ISSUE TITLE
环境疑问

### ISSUE THREAD

**Issue by ff-frida** [liujingxing/XmlClassGuard#1]
必须是jdk 11 +？
as fox+？
kt 1.6+？

**Comment by liujingxing** [comment]
没有要求

**Comment by ff-frida** [comment]
把项目的环境升级了，从AGP4升级到7，和demo一样。
在旧4.1.2插件和as4.1.2版本中是有报错，需要jdk11.
终于混淆成功了，混淆之后，自定义view的R文件需要手动导入。
如果项目中用到data binding，在xml布局中的data对应的vm的路径需要手动改过来。还好我自己项目中极少这个。就直接删除了。
转换后进行打release包。也能正常运行（初步测试）。
但是我自定义的混淆字典并没有生效。

```
    signingConfigs {
        release {
            storeFile file('../android_sign.jks')
            storePassword '234'
            keyAlias = '234'
            keyPassword '234234'
        }
    }


release {
            minifyEnabled true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField("String", "APP_BASE_URL", "\"hsdf2020\"")
            buildConfigField("String", "UNION_BASE_URL", "\"hshes.com\"")
        }
```

如果没有升级AGP7配置的字典正常的。

我先排查下是不是AGP的问题。现在就查自定义混淆字典了。
感谢大佬开源的库

**Comment by liujingxing** [comment]
自定义混淆字典？你说的是ProGuard的混淆规则？ XmlClassGuard跟ProGuard是没有任何关系的，XmlClassGuard可以看作为ProGuard的补充，弥补ProGuard不混淆四大组件等类的问题。

自定义view的R文件的话，应该是不需要手动导入的，这个有空我再验证下。

xml布局的，data binding这块确实没考虑到，后续会考虑加上
