### ISSUE TITLE
支持viewmodel吗 我看xml文件里面对应的viewmodel类名没有被跟着混淆掉

### ISSUE THREAD

**Issue by RedDargon** [liujingxing/XmlClassGuard#14]

**Comment by liujingxing** [comment]
`<data>`标签下内容，不会检索，也就不会更改这部分内容；而viewmodel类被混淆了，应该这些类跟Activity/fragment等类在同一个文件夹下，从而被一起混淆了，当前你可以将viewmodel等类移动到另一个文件夹来规避这个问题
