### ISSUE TITLE
Execution failed for task ':app:xmlClassGuard'. > java.lang.NullPointerException (no error message)

### ISSUE THREAD

**Issue by yz182** [liujingxing/XmlClassGuard#19]
![image](https://user-images.githubusercontent.com/3816646/193437215-20c97f07-c13b-44f9-95bd-52b9b088abad.png)

**Comment by yz182** [comment]
![image](https://user-images.githubusercontent.com/3816646/193437633-d57e8487-71af-4632-8aa4-985890d6faca.png)

**Comment by yz182** [comment]
![image](https://user-images.githubusercontent.com/3816646/193437691-020a4d8e-d8b9-4b34-880c-9fc849b89dcd.png)

**Comment by liujingxing** [comment]
依赖的版本号多少

**Comment by yz182** [comment]
![image](https://user-images.githubusercontent.com/3816646/193441764-58693141-9a95-4663-959b-61f5aac4340d.png)

**Comment by yz182** [comment]
单独执行 Task :app:moveDir 是可以的

**Comment by yz182** [comment]
单独执行 Task :app:packageChange 也是可以的

**Comment by yz182** [comment]
最后执行 Execution failed for task ':app:xmlClassGuard'. 失败了，具体的类名称和类目录都没有变化

**Comment by liujingxing** [comment]
先执行xmlclassguard呢

**Comment by yz182** [comment]
项目使用了databinding、viewbinding，应该没影响吧。

**Comment by liujingxing** [comment]
你的`AndroidManifest.xml`文件没有`package`属性？

**Comment by yz182** [comment]
肯定是有的撒
![image](https://user-images.githubusercontent.com/3816646/194687958-3a7175a5-6c75-44c7-9e98-5b49c3ab294a.png)

**Comment by liujingxing** [comment]
其它module呢？

**Comment by yz182** [comment]
只有一个主Module，其他都是library的

**Comment by liujingxing** [comment]
library如果有`AndroidManifest.xml`文件，则`package`属性是必须的，检查下，看日志就是没有`package`属性

**Comment by yz182** [comment]
谢谢，已解决，就是新建的library 清单文件没有package
