### ISSUE TITLE
大佬 你好，能否帮忙看下这个SAXParseException是什么原因引发的

### ISSUE THREAD

**Issue by iRootz** [liujingxing/XmlClassGuard#22]
Caused by: org.xml.sax.**SAXParseException**; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
![2095e3d0d013d4fac63c8d7da7a904b](https://user-images.githubusercontent.com/29529960/203125315-b940cc83-1d0b-436a-b5d2-af35c5f89fdd.png)

**Comment by liujingxing** [comment]
不清楚，能知道的就是你的layout文件有问题，自己排查下
