### ISSUE TITLE
Execution failed for task ':app:moveDir'. (Permission denied)

### ISSUE THREAD

**Issue by kinsunlu** [liujingxing/XmlClassGuard#26]
我在macos 12.6上面遇到了下面的错误导致我全部的Gradle命令（moveDir，packageChange，xmlClassGuard）都无法使用全部报下面的错误。
Execution failed for task ':app:moveDir'.
> java.io.FileNotFoundException: /Users/kinsun/Desktop/TestApplication/app/src/main/AndroidManifest.xml (Permission denied)

**Comment by kinsunlu** [comment]
Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
Java 11

**Comment by liujingxing** [comment]
授权as文件访问权限

**Comment by kinsunlu** [comment]
> 

![截屏2022-12-27 17 59 39](https://user-images.githubusercontent.com/16129261/209649446-d37a6c98-032a-4d22-a780-711f155664a9.png)
已经授权了还是不可以，您没有遇到该问题吗

**Comment by liujingxing** [comment]
没遇到，自己写个task测试下就知道了

**Comment by kinsunlu** [comment]
> 没遇到，自己写个task测试下就知道了

如果您方便的话，我可以加您的微信吗？

**Comment by liujingxing** [comment]
github上有
