### ISSUE TITLE
Unable to find method ''java.lang.String com.android.build.gradle.BaseExtension.getNamespace()'' 'java.lang.String com.android.build.gradle.BaseExtension.getNamespace()'

### ISSUE THREAD

**Issue by tiamosu** [liujingxing/XmlClassGuard#28]
Unable to find method ''java.lang.String com.android.build.gradle.BaseExtension.getNamespace()''
'java.lang.String com.android.build.gradle.BaseExtension.getNamespace()'

classpath 'com.android.tools.build:gradle:4.1.3'

**Comment by liujingxing** [comment]
将gralde 版本升级到最新

**Comment by tiamosu** [comment]
> 将gradle 版本升级到最新，后续版本会适配该问题

好的  多谢

**Comment by liujingxing** [comment]
v1.1.3-beta1版本已更新

**Comment by liujingxing** [comment]
v1.1.3-beta1版本已更新
