### ISSUE TITLE
Could not find com.bytedance.android:aabresguard-plugin:0.1.10.

### ISSUE THREAD

**Issue by fanyuan** [liujingxing/XmlClassGuard#3]
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.bytedance.android:aabresguard-plugin:0.1.10.
     Searched in the following locations:
       - https://maven.aliyun.com/repository/public/com/bytedance/android/aabresguard-plugin/0.1.10/aabresguard-plugin-0.1.10.pom
       - https://maven.aliyun.com/nexus/content/groups/public/com/bytedance/android/aabresguard-plugin/0.1.10/aabresguard-plugin-0.1.10.pom
       - https://jitpack.io/com/bytedance/android/aabresguard-plugin/0.1.10/aabresguard-plugin-0.1.10.pom
       - https://dl.google.com/dl/android/maven2/com/bytedance/android/aabresguard-plugin/0.1.10/aabresguard-plugin-0.1.10.pom
       - https://repo.maven.apache.org/maven2/com/bytedance/android/aabresguard-plugin/0.1.10/aabresguard-plugin-0.1.10.pom
     Required by:
         project : > com.github.liujingxing:XmlClassGuard:1.0.2

**Comment by liujingxing** [comment]
https://github.com/bytedance/AabResGuard/issues/75

**Comment by liujingxing** [comment]
[v1.0.3](https://github.com/liujingxing/XmlClassGuard/wiki#v103)版本，内部已移除`aabresgurad`
