### ISSUE TITLE
Should read manifest file path from sourceSets

### ISSUE THREAD

**Issue by yangc999** [liujingxing/XmlClassGuard#31]
I got gradle setting like:
```
sourceSets.main {
        aidl.srcDir "../java/src"
        java.srcDir "../java/src"
        manifest.srcFile "AndroidManifest.xml"
   }
```
plugin always return error like:
../src/main/AndroidManifest.xml (No such file or directory)

**Comment by liujingxing** [comment]
Fixed in the next version

**Comment by liujingxing** [comment]
[1.1.3-beta3版本已更新](https://github.com/liujingxing/XmlClassGuard/wiki)
