### ISSUE TITLE
关于android特殊工程

### ISSUE THREAD

**Issue by yfang520** [liujingxing/XmlClassGuard#32]
从unity导出的工程, 目录结构有点不一样, 报错找不到AndroidManifest.xml

报错: xxx\src\main\AndroidManifest.xml (系统找不到指定的路径。)

**Comment by liujingxing** [comment]
#31 下个版本修复

**Comment by yfang520** [comment]
哥, 不是很了解, 版本修复是修复工程目录结构吗, 能不能给个链接让我了解下, 感激!

**Comment by liujingxing** [comment]
下个版本会适配你这种工程目录结构

**Comment by yfang520** [comment]
好的, 谢谢
