### ISSUE TITLE
Manifest will not be obfuscated when res folder do not have layout sub folder

### ISSUE THREAD

**Issue by yangc999** [liujingxing/XmlClassGuard#33]
manifest should always be processed with obfuscation

**Comment by liujingxing** [comment]
I don't get it.

**Comment by yangc999** [comment]
//处理res目录
    private fun handleResDir(project: Project) {
        val listFiles = project.resDir().listFiles { _, name ->
            //过滤res目录下的layout、navigation目录
            name.startsWith("layout") || name.startsWith("navigation")
        }?.toMutableList() ?: return
        listFiles.add(project.manifestFile())
        project.files(listFiles).asFileTree.forEach { xmlFile ->
            guardXml(project, xmlFile)
        }
    }

I saw you passed the processing when layout folder not existed.

**Comment by liujingxing** [comment]
fixed in `v1.1.3-beta3`

**Comment by liujingxing** [comment]
a729ea3
