### ISSUE TITLE
xml目录下也有可能有自定义view

### ISSUE THREAD

**Issue by tangxiangpi** [liujingxing/XmlClassGuard#36]
所以，除了layout，navigation之外，xml目录（比如自定义的Preference）也需要支持替换（xmlClassGuard）自定义view的包名。

**Comment by liujingxing** [comment]
下个版本更新

**Comment by tangxiangpi** [comment]
补充下，应该是packageChange应该也需要修改吧，自定义view的java代码包名修改了，但是xml目录下引用时的包名没有修改

**Comment by tangxiangpi** [comment]
修改4大组件好像不支持多模块，比如app中一个activity集成了另外一个基础模块的Activity，基础模块Activity名字混淆了，但是代码中引用还是原来的名字。有没有可能是因为代码是kt不是java导致的，我不确定，反正结果是这样的

**Comment by tangxiangpi** [comment]
> 修改4大组件好像不支持多模块，比如app中一个activity集成了另外一个基础模块的Activity，基础模块Activity名字混淆了，但是代码中引用还是原来的名字。有没有可能是因为代码是kt不是java导致的，我不确定，反正结果是这样的

基类中这个Activity类名字有Activity，其实并不是Activity，是不是不需要混淆了

**Comment by liujingxing** [comment]
> 补充下，应该是packageChange应该也需要修改吧，自定义view的java代码包名修改了，但是xml目录下引用时的包名没有修改

3个任务都会需要同步修改

**Comment by liujingxing** [comment]
> > 修改4大组件好像不支持多模块，比如app中一个activity集成了另外一个基础模块的Activity，基础模块Activity名字混淆了，但是代码中引用还是原来的名字。有没有可能是因为代码是kt不是java导致的，我不确定，反正结果是这样的
> 
> 基类中这个Activity类名字有Activity，其实并不是Activity，是不是不需要混淆了

被xml引用的类，以及跟这些类在同一包下的类，都会被混淆

**Comment by liujingxing** [comment]
> 修改4大组件好像不支持多模块，比如app中一个activity集成了另外一个基础模块的Activity，基础模块Activity名字混淆了，但是代码中引用还是原来的名字。有没有可能是因为代码是kt不是java导致的，我不确定，反正结果是这样的

3个任务的作用域都是整个项目，而不是某个模块，这个问题需要具体分析

**Comment by liujingxing** [comment]
请先确认升级到了目前最新版本`1.1.3-beta3`

**Comment by tangxiangpi** [comment]
> 请先确认升级到了目前最新版本`1.1.3-beta3`
确认的啦
![image](https://user-images.githubusercontent.com/18000558/228118778-ca9678a5-f17e-43a8-bdff-7433adbfb471.png)
