### ISSUE TITLE
如果使用navigation架构开发的话，fragment混淆后，代码里面调用Directions地方没有替换成混淆后的

### ISSUE THREAD

**Issue by jcadmin** [liujingxing/XmlClassGuard#38]
如果使用navigation架构开发的话，fragment混淆后，代码里面调用Directions地方没有替换成混淆后的，比如TestFragment混淆成D，生成的TestFragmentDirections,混淆后应该是DDirections，但是代码调用的还是TestFragmentDirections，这个怎么处理

**Comment by liujingxing** [comment]
暂时你只能手动改

**Comment by jcadmin** [comment]
代码拉下来改了源码基本处理好了

**Comment by liujingxing** [comment]
欢迎提PR
