### ISSUE TITLE
使用moveDir功能有bug

### ISSUE THREAD

**Issue by 18319557579** [liujingxing/XmlClassGuard#45]
我的想法是将这5个类移动到screen目录下，但是好像做不到。我使用下面这样的语句：
![a6ad2a468c1d09409aa786568ff8e6d](https://github.com/liujingxing/XmlClassGuard/assets/79951233/cf2a55ab-26e6-4fb5-93eb-c9c8396616fa)

结果是类都给删除了
![72eae2702c3ad7f3f0c70ab93500b86](https://github.com/liujingxing/XmlClassGuard/assets/79951233/9a72d75b-daaf-449f-b7b9-ace9b7da6c14)

这种需求用该插件能实现吗？

**Comment by liujingxing** [comment]
版本号多少？  moveDir任务是将某个目录下的文件及文件夹移动到另外一个目录下，原目录肯定是会删除的，新目录下可以找到

**Comment by liujingxing** [comment]
知道了，你这个目标目录在原始目录下，，这点没考虑到；代码的执行逻辑是，拷贝完成后，删除原始目录

**Comment by 18319557579** [comment]
那后续这个执行逻辑打算改吗，蹲一手

**Comment by liujingxing** [comment]
会改的

**Comment by liujingxing** [comment]
1befb12074e36eedb578aa89fef73f1838e0972e

**Comment by liujingxing** [comment]
[v1.2.4](https://github.com/liujingxing/XmlClassGuard/wiki#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)版本已更新
