### ISSUE TITLE
layout xml文件中 的tools:context=".RandomActivity" 不能被正确替换

### ISSUE THREAD

**Issue by adolfodoriano** [liujingxing/XmlClassGuard#47]
执行packagechange任务时，如果.RandomActivity 不带包名，不会像Manifest.xml一样补齐包名。

执行xmlClassGuard任务时，tools:context=也不会指向 对应的 更名后的 Activity 类名。

**Comment by liujingxing** [comment]
这个没考虑到

**Comment by liujingxing** [comment]
app:layoutManager  属性也一样

**Comment by liujingxing** [comment]
[v1.2.4](https://github.com/liujingxing/XmlClassGuard/wiki#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)版本已更新
