### ISSUE TITLE
一定要和aabresguard一起使用吗？

### ISSUE THREAD

**Issue by lindan83** [liujingxing/XmlClassGuard#5]
如果项目不需要依赖于aabresguard，构建时会报错：Could not find com.bytedance.android:aabresguard-plugin:0.1.10.

但是项目又不想引入aabresguard。

**Comment by liujingxing** [comment]
没有要求

**Comment by liujingxing** [comment]
https://github.com/liujingxing/XmlClassGuard/issues/3

**Comment by liujingxing** [comment]
[v1.0.3](https://github.com/liujingxing/XmlClassGuard/wiki#v103)版本，内部已移除`aabresgurad`
