### ISSUE TITLE
可以支持layout里app:layout_behavior 使用自定义类

### ISSUE THREAD

**Issue by samli139** [liujingxing/XmlClassGuard#53]
目前如果layout里app:layout_behavior有自定义的类时，自定类已经被改了，但这个地方没有改过来，希望后续版本能支持这个，谢谢！

**Comment by liujingxing** [comment]
试试1.2.5-beta1版本

**Comment by liujingxing** [comment]
[v1.2.5版本已更新](https://github.com/liujingxing/XmlClassGuard/wiki)
