### ISSUE TITLE
项目里面的aidl生成的文件找不到对应的类

### ISSUE THREAD

**Issue by myPolaris** [liujingxing/XmlClassGuard#54]

**Comment by myPolaris** [comment]
这种应该怎么去解决？

**Comment by liujingxing** [comment]
请详细描述

**Comment by myPolaris** [comment]
![飞书20230904-112059](https://github.com/liujingxing/XmlClassGuard/assets/10556331/5c30a1da-bba5-44d0-bbb0-e9f674359ed7)
![飞书20230904-112106](https://github.com/liujingxing/XmlClassGuard/assets/10556331/e320a706-1e61-466b-886b-7d53341ba755)
这是我的项目xml配置，配置完之后，对应的aidl没有生成对应文件，导致项目里面的aidl路径找不到文件

**Comment by myPolaris** [comment]
不知道是不是因为packagename修改了，导致aidl没有生成对应的java文件

**Comment by myPolaris** [comment]
@liujingxing

**Comment by liujingxing** [comment]
暂时先手动更改，下版本会适配

**Comment by liujingxing** [comment]
[v1.2.5版本已更新](https://github.com/liujingxing/XmlClassGuard/wiki)
