### ISSUE TITLE
不同包名相同类名混淆失败

### ISSUE THREAD

**Issue by xujianfen** [liujingxing/XmlClassGuard#60]
当一个类，如aa.A使用了bb.B类，A所在的包有一个aa.B类时，这时候混淆后会出现问题， bb.B会被当做aa.B，import  bb.B会被去掉，导致使用了错误的B，如果不直接用B，而是使用bb.B就不会出现问题。

**Comment by liujingxing** [comment]
误杀问题暂时无法避免，请手动规避

**Comment by xujianfen** [comment]
相同文件下出现同类名不同包名会出现混淆混乱的情况，这个是同样的原因吗

**Comment by liujingxing** [comment]
理论上只有类名相同会出现误杀的情况

**Comment by xujianfen** [comment]
好的，感谢回复
