### ISSUE TITLE
packageChange在使用Gradle 8.0后的变化

### ISSUE THREAD

**Issue by hpdx** [liujingxing/XmlClassGuard#63]
`packageChange = ["com.shenglang.mvi.playandroid" : "ggg.kkk"]`

 在引入namespace之前，确实README文档里所描述的那样

在使用Gradle 8.0后，`packageChange` 更改的是build.gradle里namespace属性的值，R文件的引用会变

**Comment by liujingxing** [comment]
这有什么不对吗？namespace属性的指，及`AndroidManifest.xml`文件里的package属性代表R文件的引用路径

**Comment by hpdx** [comment]
@liujingxing  没有什么不对，提这个issue的意义在帮助后面使用这个库的人。我昨天按你写的README里的步骤，已经测试通过了。
